### ISSUE TITLE
The switch repos in the fork may not work

### ISSUE THREAD

**Issue by tomio13** [elabftw/elabdoc#20]
**Describe the bug**
The documentation says:
~~~ markdown
Go on [the repository on GitHub](https://github.com/elabftw/elabftw)
    Click the Star button (it helps with visibility of the project)
    Click the Fork button in the top right of the screen
    From your fork page, clone it with SSH on your machine:

git clone git@github.com:<YOUR USERNAME>/elabftw.git
# checkout the hypernext branch because this is where dev happens
cd elabftw
git checkout hypernext
cd ..
A clear and concise description of what the bug is.
~~~

But if I fork, I fork a branch, and I do not have the hypernext in the local branch. I have to fork the hypernext branch, then I can pull it, but for me it shall be my master branch. Or there is a step I did not get... 
**To Reproduce**
1. go to the elabftw/elabftw master branch, and make a fork
2. make the local dir, and do the cloning as described
3. try to switch branch with git

I think, you simply have to fork the hypernext branch, and clone that one.

**Comment by NicolasCARPi** [comment]
So apparently now when you click "Fork", you have a screen where you can check/uncheck "Copy the `master` branch only". So you need to uncheck this I guess, so all branches are present. I'll adjust the documentation.

**Comment by tomio13** [comment]
Super, thank you. At the end I had to go the long way... github allows that you have your local branch, then on your computer you do:

~~~bash
# list the actual remote part
git remote -v
# add the upstream
git remote add upstream https://github.com/elabftw/elabftw.git
git fetch upstream
# now merge the upstream/hypernext to my main branch
git merge upstream/hypernext
# and push it back to your fork repo
git push
~~~
Based on the documentation of [Configuring a remote repository for a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork) and [Syncing a fork branch from the command line](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-command-line).
